services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - .:/works
      - next_build:/works/.next
      - node_modules:/works/node_modules
    restart: no
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules:
  next_build: